//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="VinniesLoanServiceSoap", Namespace="http://tempuri.org/")]
public partial class VinniesLoanService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback LoanPaymentOperationCompleted;
    
    /// <remarks/>
    public VinniesLoanService() {
        this.Url = "http://localhost:49215/VinniesLoanService.asmx";
    }
    
    /// <remarks/>
    public event LoanPaymentCompletedEventHandler LoanPaymentCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoanPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public float LoanPayment(float principle, float rate, int payments) {
        object[] results = this.Invoke("LoanPayment", new object[] {
                    principle,
                    rate,
                    payments});
        return ((float)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLoanPayment(float principle, float rate, int payments, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LoanPayment", new object[] {
                    principle,
                    rate,
                    payments}, callback, asyncState);
    }
    
    /// <remarks/>
    public float EndLoanPayment(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((float)(results[0]));
    }
    
    /// <remarks/>
    public void LoanPaymentAsync(float principle, float rate, int payments) {
        this.LoanPaymentAsync(principle, rate, payments, null);
    }
    
    /// <remarks/>
    public void LoanPaymentAsync(float principle, float rate, int payments, object userState) {
        if ((this.LoanPaymentOperationCompleted == null)) {
            this.LoanPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoanPaymentOperationCompleted);
        }
        this.InvokeAsync("LoanPayment", new object[] {
                    principle,
                    rate,
                    payments}, this.LoanPaymentOperationCompleted, userState);
    }
    
    private void OnLoanPaymentOperationCompleted(object arg) {
        if ((this.LoanPaymentCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LoanPaymentCompleted(this, new LoanPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void LoanPaymentCompletedEventHandler(object sender, LoanPaymentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LoanPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LoanPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public float Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((float)(this.results[0]));
        }
    }
}
