//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="TextServiceSoap", Namespace="http://localhost/webservice/")]
public partial class TextService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback CaseConvertOperationCompleted;
    
    /// <remarks/>
    public TextService() {
        this.Url = "http://localhost:49215/TextService.asmx";
    }
    
    /// <remarks/>
    public event CaseConvertCompletedEventHandler CaseConvertCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webservice/CaseConvert", RequestNamespace="http://localhost/webservice/", ResponseNamespace="http://localhost/webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string CaseConvert(string incoming, uint flag) {
        object[] results = this.Invoke("CaseConvert", new object[] {
                    incoming,
                    flag});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCaseConvert(string incoming, uint flag, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CaseConvert", new object[] {
                    incoming,
                    flag}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndCaseConvert(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void CaseConvertAsync(string incoming, uint flag) {
        this.CaseConvertAsync(incoming, flag, null);
    }
    
    /// <remarks/>
    public void CaseConvertAsync(string incoming, uint flag, object userState) {
        if ((this.CaseConvertOperationCompleted == null)) {
            this.CaseConvertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCaseConvertOperationCompleted);
        }
        this.InvokeAsync("CaseConvert", new object[] {
                    incoming,
                    flag}, this.CaseConvertOperationCompleted, userState);
    }
    
    private void OnCaseConvertOperationCompleted(object arg) {
        if ((this.CaseConvertCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CaseConvertCompleted(this, new CaseConvertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void CaseConvertCompletedEventHandler(object sender, CaseConvertCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CaseConvertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CaseConvertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
