//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="TickerTapeSoap", Namespace="http://tempuri.org/")]
public partial class TickerTape : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetQuoteOperationCompleted;
    
    /// <remarks/>
    public TickerTape() {
        this.Url = "http://localhost:49215/TickerTape.asmx";
    }
    
    /// <remarks/>
    public event GetQuoteCompletedEventHandler GetQuoteCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetQuote", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public QuoteInfo GetQuote(string tickerSymbol) {
        object[] results = this.Invoke("GetQuote", new object[] {
                    tickerSymbol});
        return ((QuoteInfo)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetQuote(string tickerSymbol, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetQuote", new object[] {
                    tickerSymbol}, callback, asyncState);
    }
    
    /// <remarks/>
    public QuoteInfo EndGetQuote(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((QuoteInfo)(results[0]));
    }
    
    /// <remarks/>
    public void GetQuoteAsync(string tickerSymbol) {
        this.GetQuoteAsync(tickerSymbol, null);
    }
    
    /// <remarks/>
    public void GetQuoteAsync(string tickerSymbol, object userState) {
        if ((this.GetQuoteOperationCompleted == null)) {
            this.GetQuoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQuoteOperationCompleted);
        }
        this.InvokeAsync("GetQuote", new object[] {
                    tickerSymbol}, this.GetQuoteOperationCompleted, userState);
    }
    
    private void OnGetQuoteOperationCompleted(object arg) {
        if ((this.GetQuoteCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetQuoteCompleted(this, new GetQuoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class QuoteInfo {
    
    private string symbolField;
    
    private double lastPriceField;
    
    private string lastPriceDateField;
    
    private string lastPriceTimeField;
    
    /// <remarks/>
    public string Symbol {
        get {
            return this.symbolField;
        }
        set {
            this.symbolField = value;
        }
    }
    
    /// <remarks/>
    public double LastPrice {
        get {
            return this.lastPriceField;
        }
        set {
            this.lastPriceField = value;
        }
    }
    
    /// <remarks/>
    public string LastPriceDate {
        get {
            return this.lastPriceDateField;
        }
        set {
            this.lastPriceDateField = value;
        }
    }
    
    /// <remarks/>
    public string LastPriceTime {
        get {
            return this.lastPriceTimeField;
        }
        set {
            this.lastPriceTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetQuoteCompletedEventHandler(object sender, GetQuoteCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetQuoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetQuoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public QuoteInfo Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((QuoteInfo)(this.results[0]));
        }
    }
}
