<%
   sFld=request.querystring("fld") 
   tmp=request.querystring("eref") 
   
   tabName="language"
   if(tmp = "Y") then tabName="languageERef"
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=ISO-8859-1">
<LINK href="../../css/styles.css" rel=styleSheet type=text/css>	
<title>Clarity Healthcare</title>
<style type="text/css">
body{font-family:verdana,arial,helvetica;font-size:8pt;color:red;margin:10;background:#ffffff;}

th{font-family:verdana,arial,helvetica;font-size:8pt;font-weight:600;color:#000066;background:#dff1ff;}
td{font-family:verdana,arial,helvetica;font-size:8pt;background:#dff1ff;}
td.hdg{font-weight:600;color:#000066;}
a:link{text-decoration:none;color:#000066;}
a.selDate:link:{background:white;color:#0000CC;}
a:hover{color:#000066;background:#FFFFCC;}
</style>
<script language="Javascript">
function returncode(d){
  window.opener.document.forms[0].elements['<%=sFld%>'].value=d;
  window.close();
  window.opener.focus();
}
</script>
</head>
<body onload="self.focus();" leftMargin="10" topMargin="0" marginwidth="0" marginheight="0">
	<table border="1" cellpadding="2" cellspacing="0" width="400" bordercolor="#AABBCC">
	<b><span class="fieldlabels"><center>ISO Language Lookup</center></span><p>
	<img name=print src='../../images/printicon.gif' width='15' height='11' alt='' border='0'>&nbsp;<a href=javascript:window.print()>Print</a>
	<tr>
		<td bordercolor="#CCDDEE" bgcolor="#f4f5e1" valign="top">
			<form name="F1" method=post action=lookupLanguage.asp?fld=<%=request.querystring("fld")%>&eref=<%=Request.QueryString("eref")%>>Quick Search:<input type=hidden name=mode value="search"><input type=text size=20 maxsize=20 name=search><input type="image" src="../../images/go-button.gif"></form>
		</td>
	  <td>
        &nbsp;&nbsp;&nbsp;<img name=close src='../../images/reminder.gif' width='15' height='11' alt='Close Window' border='0'>&nbsp;<a href=javascript:parent.close()>Close</a>
	  </td>
	</tr>
	</table><br>
<!-- form never actually posted -->
<%
mode=request("mode")
	response.write("<table>")
	Response.write "<td width=150 align=center class='fieldlabels'>Code</td><td width=20>&nbsp;</td><td width=270 class='fieldlabels'>Description</td>"
    Response.write "<tr><td width=150 align=center>abk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('abk')"">Abkhazian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ace</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ace')"">Achinese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ach</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ach')"">Acoli</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ada</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ada')"">Adangme</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ady</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ady')"">Adyghe; Adygei</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>aar</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('aar')"">Afar</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>afh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('afh')"">Afrihili</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>afr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('afr')"">Afrikaans</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>afa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('afa')"">Afro-Asiatic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ain</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ain')"">Ainu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>aka</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('aka')"">Akan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>akk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('akk')"">Akkadian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>alb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('alb')"">Albanian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ale</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ale')"">Aleut</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>alg</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('alg')"">Algonquian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qad</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qad')"">Algonquin</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tut</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tut')"">Altaic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qaa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qaa')"">American Sign Language</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>amh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('amh')"">Amharic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>anp</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('anp')"">Angika</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>apa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('apa')"">Apache languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ara</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ara')"">Arabic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>arg</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('arg')"">Aragonese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>arp</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('arp')"">Arapaho</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>arw</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('arw')"">Arawak</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>arm</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('arm')"">Armenian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>rup</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('rup')"">Aromanian; Arumanian; Macedo-Romanian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>art</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('art')"">Artificial languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>asm</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('asm')"">Assamese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ast</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ast')"">Asturian; Bable; Leonese; Asturleonese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ath</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ath')"">Athapascan languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qae</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qae')"">Attikamek</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>aus</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('aus')"">Australian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>map</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('map')"">Austronesian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ava</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ava')"">Avaric</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ave</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ave')"">Avestan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>awa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('awa')"">Awadhi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>aym</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('aym')"">Aymara</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>aze</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('aze')"">Azerbaijani</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ban</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ban')"">Balinese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bat</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bat')"">Baltic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bal</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bal')"">Baluchi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bam</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bam')"">Bambara</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bai</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bai')"">Bamileke languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bad</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bad')"">Banda languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bnt</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bnt')"">Bantu languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bas</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bas')"">Basa</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bak</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bak')"">Bashkir</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>baq</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('baq')"">Basque</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>btk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('btk')"">Batak languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bej</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bej')"">Beja; Bedawiyet</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bel</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bel')"">Belarusian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bem</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bem')"">Bemba</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ben</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ben')"">Bengali</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ber</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ber')"">Berber languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bho</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bho')"">Bhojpuri</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bih</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bih')"">Bihari languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bik</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bik')"">Bikol</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bin</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bin')"">Bini; Edo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bis</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bis')"">Bislama</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>byn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('byn')"">Blin; Bilin</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>zbl</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('zbl')"">Blissymbols; Blissymbolics; Bliss</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nob</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nob')"">Bokmål, Norwegian; Norwegian Bokmål</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bos</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bos')"">Bosnian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bra</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bra')"">Braj</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bre</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bre')"">Breton</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bug</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bug')"">Buginese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bul</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bul')"">Bulgarian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bua</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bua')"">Buriat</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bur</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bur')"">Burmese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cad</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cad')"">Caddo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qav</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qav')"">Cantonese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qaf</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qaf')"">Carrier</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cat</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cat')"">Catalan; Valencian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cau</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cau')"">Caucasian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ceb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ceb')"">Cebuano</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cel</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cel')"">Celtic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cai</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cai')"">Central American Indian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>khm</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('khm')"">Central Khmer</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chg</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chg')"">Chagatai</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cmc</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cmc')"">Chamic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cha</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cha')"">Chamorro</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>che</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('che')"">Chechen</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chr')"">Cherokee</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chy</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chy')"">Cheyenne</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chb')"">Chibcha</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nya</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nya')"">Chichewa; Chewa; Nyanja</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qag</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qag')"">Chilcontin</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chi')"">Chinese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chn')"">Chinook jargon</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chp</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chp')"">Chipewyan; Dene Suline</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cho</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cho')"">Choctaw</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chu</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chu')"">Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chk')"">Chuukese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chv</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chv')"">Chuvash</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nwc</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nwc')"">Classical Newari; Old Newari; Classical Nepal Bhasa</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>syc</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('syc')"">Classical Syriac</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cop</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cop')"">Coptic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cor</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cor')"">Cornish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cos</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cos')"">Corsican</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cre</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cre')"">Cree</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mus</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mus')"">Creek</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>crp</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('crp')"">Creoles and pidgins</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cpe</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cpe')"">Creoles and pidgins, English based</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cpf</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cpf')"">Creoles and pidgins, French-based</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cpp</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cpp')"">Creoles and pidgins, Portuguese-based</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>crh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('crh')"">Crimean Tatar; Crimean Turkish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hrv</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hrv')"">Croatian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cus</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cus')"">Cushitic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>cze</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('cze')"">Czech</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dak</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dak')"">Dakota</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dan</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dan')"">Danish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dar</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dar')"">Dargwa</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>del</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('del')"">Delaware</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>din</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('din')"">Dinka</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>div</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('div')"">Divehi; Dhivehi; Maldivian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>doi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('doi')"">Dogri</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dgr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dgr')"">Dogrib</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dra</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dra')"">Dravidian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dua</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dua')"">Duala</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dum</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dum')"">Dutch, Middle (ca.1050-1350)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dut</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dut')"">Dutch; Flemish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dyu</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dyu')"">Dyula</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dzo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dzo')"">Dzongkha</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>frs</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('frs')"">Eastern Frisian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>efi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('efi')"">Efik</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>egy</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('egy')"">Egyptian (Ancient)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>eka</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('eka')"">Ekajuk</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>elx</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('elx')"">Elamite</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>eng</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('eng')"">English</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>enm</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('enm')"">English, Middle (1100-1500)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ang</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ang')"">English, Old (ca.450-1100)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>myv</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('myv')"">Erzya</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>epo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('epo')"">Esperanto</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>est</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('est')"">Estonian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ewe</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ewe')"">Ewe</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ewo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ewo')"">Ewondo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fan</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fan')"">Fang</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fat</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fat')"">Fanti</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fao</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fao')"">Faroese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fij</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fij')"">Fijian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fil</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fil')"">Filipino; Pilipino</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fin</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fin')"">Finnish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fiu</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fiu')"">Finno-Ugrian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fon</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fon')"">Fon</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fre</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fre')"">French</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qab</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qab')"">French Sign Language</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>frm</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('frm')"">French, Middle (ca.1400-1600)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fro</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fro')"">French, Old (842-ca.1400)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fur</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fur')"">Friulian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ful</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ful')"">Fulah</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gaa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gaa')"">Ga</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gla</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gla')"">Gaelic; Scottish Gaelic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>car</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('car')"">Galibi Carib</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>glg</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('glg')"">Galician</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lug</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lug')"">Ganda</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gay</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gay')"">Gayo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gba</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gba')"">Gbaya</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gez</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gez')"">Geez</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>geo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('geo')"">Georgian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ger</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ger')"">German</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gmh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gmh')"">German, Middle High (ca.1050-1500)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>goh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('goh')"">German, Old High (ca.750-1050)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gem</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gem')"">Germanic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gil</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gil')"">Gilbertese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qai</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qai')"">Gitksan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gon</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gon')"">Gondi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gor</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gor')"">Gorontalo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>got</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('got')"">Gothic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>grb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('grb')"">Grebo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>grc</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('grc')"">Greek, Ancient (to 1453)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gre</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gre')"">Greek, Modern (1453-)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>grn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('grn')"">Guarani</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>guj</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('guj')"">Gujarati</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gwi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gwi')"">Gwich`in</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hai</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hai')"">Haida</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hat</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hat')"">Haitian; Haitian Creole</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qaw</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qaw')"">Hakka</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qaj</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qaj')"">Han</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hau</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hau')"">Hausa</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>haw</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('haw')"">Hawaiian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>heb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('heb')"">Hebrew</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>her</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('her')"">Herero</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hil</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hil')"">Hiligaynon</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>him</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('him')"">Himachali languages; Western Pahari languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hin</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hin')"">Hindi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hmo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hmo')"">Hiri Motu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hit</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hit')"">Hittite</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hmn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hmn')"">Hmong; Mong</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hun</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hun')"">Hungarian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hup</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hup')"">Hupa</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>iba</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('iba')"">Iban</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ice</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ice')"">Icelandic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ido</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ido')"">Ido</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ibo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ibo')"">Igbo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ijo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ijo')"">Ijo languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ilo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ilo')"">Iloko</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>smn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('smn')"">Inari Sami</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>inc</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('inc')"">Indic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ine</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ine')"">Indo-European languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ind</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ind')"">Indonesian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>inh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('inh')"">Ingush</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ina</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ina')"">Interlingua (International Auxiliary Language Association)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ile</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ile')"">Interlingue; Occidental</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>iku</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('iku')"">Inuktitut</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ipk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ipk')"">Inupiaq</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ira</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ira')"">Iranian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gle</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gle')"">Irish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mga</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mga')"">Irish, Middle (900-1200)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sga</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sga')"">Irish, Old (to 900)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>iro</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('iro')"">Iroquoian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ita</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ita')"">Italian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>jpn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('jpn')"">Japanese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>jav</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('jav')"">Javanese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>jrb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('jrb')"">Judeo-Arabic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>jpr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('jpr')"">Judeo-Persian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kbd</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kbd')"">Kabardian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kab</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kab')"">Kabyle</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kac</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kac')"">Kachin; Jingpho</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kal</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kal')"">Kalaallisut; Greenlandic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>xal</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('xal')"">Kalmyk; Oirat</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kam</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kam')"">Kamba</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kan</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kan')"">Kannada</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kau</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kau')"">Kanuri</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>krc</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('krc')"">Karachay-Balkar</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kaa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kaa')"">Kara-Kalpak</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>krl</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('krl')"">Karelian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kar</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kar')"">Karen languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kas</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kas')"">Kashmiri</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>csb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('csb')"">Kashubian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kaw</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kaw')"">Kawi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kaz</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kaz')"">Kazakh</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kha</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kha')"">Khasi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>khi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('khi')"">Khoisan languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kho</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kho')"">Khotanese, Sakan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kik</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kik')"">Kikuyu; Gikuyu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kmb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kmb')"">Kimbundu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kin</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kin')"">Kinyarwanda</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kir</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kir')"">Kirghiz; Kyrgyz</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tlh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tlh')"">Klingon; tlhIngan-Hol</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kom</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kom')"">Komi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kon</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kon')"">Kongo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kok</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kok')"">Konkani</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kor</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kor')"">Korean</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kos</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kos')"">Kosraean</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kpe</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kpe')"">Kpelle</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kro</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kro')"">Kru languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kua</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kua')"">Kuanyama; Kwanyama</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kum</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kum')"">Kumyk</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kur</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kur')"">Kurdish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kru</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kru')"">Kurukh</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>kut</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('kut')"">Kutenai</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lad</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lad')"">Ladino</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lah</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lah')"">Lahnda</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lam</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lam')"">Lamba</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>day</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('day')"">Land Dayak languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lao</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lao')"">Lao</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lat</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lat')"">Latin</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lav</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lav')"">Latvian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lez</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lez')"">Lezghian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lim</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lim')"">Limburgan; Limburger; Limburgish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lin</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lin')"">Lingala</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lit</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lit')"">Lithuanian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>jbo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('jbo')"">Lojban</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nds</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nds')"">Low German; Low Saxon; German, Low; Saxon, Low</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>dsb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('dsb')"">Lower Sorbian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>loz</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('loz')"">Lozi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lub</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lub')"">Luba-Katanga</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lua</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lua')"">Luba-Lulua</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lui</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lui')"">Luiseno</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>smj</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('smj')"">Lule Sami</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lun</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lun')"">Lunda</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>luo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('luo')"">Luo (Kenya and Tanzania)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lus</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lus')"">Lushai</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ltz</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ltz')"">Luxembourgish; Letzeburgesch</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mac</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mac')"">Macedonian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mad</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mad')"">Madurese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mag</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mag')"">Magahi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mai</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mai')"">Maithili</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mak</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mak')"">Makasar</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mlg</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mlg')"">Malagasy</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>may</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('may')"">Malay</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mal</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mal')"">Malayalam</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qak</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qak')"">Malecite</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mlt</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mlt')"">Maltese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mnc</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mnc')"">Manchu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mdr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mdr')"">Mandar</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qax</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qax')"">Mandarin</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>man</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('man')"">Mandingo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mni</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mni')"">Manipuri</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mno</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mno')"">Manobo languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qal</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qal')"">Mantagnais-Naskapi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>glv</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('glv')"">Manx</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mao</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mao')"">Maori</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>arn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('arn')"">Mapudungun; Mapuche</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mar</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mar')"">Marathi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>chm</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('chm')"">Mari</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mah</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mah')"">Marshallese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mwr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mwr')"">Marwari</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mas</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mas')"">Masai</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>myn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('myn')"">Mayan languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>men</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('men')"">Mende</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mic</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mic')"">Mi`kmaq; Micmac</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>min</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('min')"">Minangkabau</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mwl</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mwl')"">Mirandese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>moh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('moh')"">Mohawk</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mdf</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mdf')"">Moksha</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>lol</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('lol')"">Mongo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mon</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mon')"">Mongolian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mkh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mkh')"">Mon-Khmer languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qay</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qay')"">Montagnais Innu (Innu-Aimun, Innu Aionun</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mos</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mos')"">Mossi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mul</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mul')"">Multiple languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mun</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mun')"">Munda languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nqo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nqo')"">N`Ko</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nah</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nah')"">Nahuatl languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nau</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nau')"">Nauru</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nav</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nav')"">Navajo; Navaho</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nde</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nde')"">Ndebele, North; North Ndebele</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nbl</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nbl')"">Ndebele, South; South Ndebele</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ndo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ndo')"">Ndonga</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nap</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nap')"">Neapolitan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>new</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('new')"">Nepal Bhasa; Newari</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nep</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nep')"">Nepali</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nia</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nia')"">Nias</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nic</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nic')"">Niger-Kordofanian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ssa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ssa')"">Nilo-Saharan languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qam</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qam')"">Nishga</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>niu</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('niu')"">Niuean</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>zxx</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('zxx')"">No linguistic content; Not applicable</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nog</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nog')"">Nogai</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qan</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qan')"">Nootka</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>non</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('non')"">Norse, Old</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nai</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nai')"">North American Indian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qao</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qao')"">North Slave (Hare)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>frr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('frr')"">Northern Frisian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sme</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sme')"">Northern Sami</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qap</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qap')"">Northern Tutchone</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nor</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nor')"">Norwegian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nno</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nno')"">Norwegian Nynorsk; Nynorsk, Norwegian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nub</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nub')"">Nubian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nym</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nym')"">Nyamwezi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nyn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nyn')"">Nyankole</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nyo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nyo')"">Nyoro</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nzi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nzi')"">Nzima</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>oci</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('oci')"">Occitan (post 1500)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>arc</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('arc')"">Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>oji</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('oji')"">Ojibwa</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qaq</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qaq')"">Oji-Cree</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ori</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ori')"">Oriya</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>orm</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('orm')"">Oromo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>osa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('osa')"">Osage</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>oss</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('oss')"">Ossetian; Ossetic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>oto</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('oto')"">Otomian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pal</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pal')"">Pahlavi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pau</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pau')"">Palauan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pli</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pli')"">Pali</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pam</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pam')"">Pampanga, Kapampangan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pag</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pag')"">Pangasinan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pan</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pan')"">Panjabi; Punjabi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pap</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pap')"">Papiamento</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>paa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('paa')"">Papuan languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>nso</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('nso')"">Pedi; Sepedi; Northern Sotho</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>per</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('per')"">Persian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>peo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('peo')"">Persian, Old (ca.600-400 B.C.)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>phi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('phi')"">Philippine languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>phn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('phn')"">Phoenician</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pon</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pon')"">Pohnpeian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pol</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pol')"">Polish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>por</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('por')"">Portuguese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pra</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pra')"">Prakrit languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pro</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pro')"">Provençal, Old (to 1500); Occitan, Old (to 1500)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>pus</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('pus')"">Pushto; Pashto</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qac</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qac')"">Quebec Sign Language</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>que</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('que')"">Quechua</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>raj</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('raj')"">Rajasthani</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>rap</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('rap')"">Rapanui</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>rar</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('rar')"">Rarotongan; Cook Islands Maori</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>roa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('roa')"">Romance languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>rum</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('rum')"">Romanian; Moldavian; Moldovan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>roh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('roh')"">Romansh</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>rom</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('rom')"">Romany</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>run</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('run')"">Rundi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>rus</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('rus')"">Russian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sal</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sal')"">Salishan languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sam</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sam')"">Samaritan Aramaic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>smi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('smi')"">Sami languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>smo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('smo')"">Samoan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sad</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sad')"">Sandawe</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sag</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sag')"">Sango</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>san</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('san')"">Sanskrit</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sat</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sat')"">Santali</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>srd</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('srd')"">Sardinian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sas</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sas')"">Sasak</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sco</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sco')"">Scots</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sel</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sel')"">Selkup</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sem</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sem')"">Semitic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>srp</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('srp')"">Serbian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>srr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('srr')"">Serer</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>shn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('shn')"">Shan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sna</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sna')"">Shona</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qar</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qar')"">Shuswap</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>iii</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('iii')"">Sichuan Yi; Nuosu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>scn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('scn')"">Sicilian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sid</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sid')"">Sidamo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sgn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sgn')"">Sign Languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>bla</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('bla')"">Siksika</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>snd</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('snd')"">Sindhi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sin</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sin')"">Sinhala; Sinhalese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sit</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sit')"">Sino-Tibetan languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sio</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sio')"">Siouan languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sms</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sms')"">Skolt Sami</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>den</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('den')"">Slave (Athapascan)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sla</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sla')"">Slavic languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>slo</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('slo')"">Slovak</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>slv</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('slv')"">Slovenian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sog</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sog')"">Sogdian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>som</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('som')"">Somali</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>son</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('son')"">Songhai languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>snk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('snk')"">Soninke</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>wen</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('wen')"">Sorbian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sot</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sot')"">Sotho, Southern</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sai</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sai')"">South American Indian languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qas</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qas')"">South Slave</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>alt</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('alt')"">Southern Altai</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sma</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sma')"">Southern Sami</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qat</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qat')"">Southern Tutchone</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>spa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('spa')"">Spanish; Castilian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>srn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('srn')"">Sranan Tongo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>suk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('suk')"">Sukuma</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sux</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sux')"">Sumerian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sun</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sun')"">Sundanese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sus</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sus')"">Susu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>swa</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('swa')"">Swahili</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ssw</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ssw')"">Swati</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>swe</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('swe')"">Swedish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>gsw</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('gsw')"">Swiss German; Alemannic; Alsatian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>syr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('syr')"">Syriac</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tgl</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tgl')"">Tagalog</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tah</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tah')"">Tahitian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tai</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tai')"">Tai languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tgk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tgk')"">Tajik</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tmh</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tmh')"">Tamashek</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tam</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tam')"">Tamil</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tat</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tat')"">Tatar</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tel</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tel')"">Telugu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ter</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ter')"">Tereno</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tet</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tet')"">Tetum</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tha</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tha')"">Thai</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>qau</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('qau')"">Thompson (Ntlakapamux)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tib</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tib')"">Tibetan</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tig</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tig')"">Tigre</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tir</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tir')"">Tigrinya</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tem</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tem')"">Timne</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tiv</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tiv')"">Tiv</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tli</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tli')"">Tlingit</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tpi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tpi')"">Tok Pisin</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tkl</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tkl')"">Tokelau</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tog</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tog')"">Tonga (Nyasa)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ton</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ton')"">Tonga (Tonga Islands)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tsi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tsi')"">Tsimshian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tso</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tso')"">Tsonga</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tsn</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tsn')"">Tswana</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tum</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tum')"">Tumbuka</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tup</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tup')"">Tupi languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tur</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tur')"">Turkish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ota</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ota')"">Turkish, Ottoman (1500-1928)</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tuk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tuk')"">Turkmen</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tvl</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tvl')"">Tuvalu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>tyv</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('tyv')"">Tuvinian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>twi</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('twi')"">Twi</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>udm</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('udm')"">Udmurt</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>uga</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('uga')"">Ugaritic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>uig</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('uig')"">Uighur; Uyghur</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ukr</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ukr')"">Ukrainian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>umb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('umb')"">Umbundu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>mis</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('mis')"">Uncoded languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>und</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('und')"">Undetermined</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>hsb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('hsb')"">Upper Sorbian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>urd</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('urd')"">Urdu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>uzb</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('uzb')"">Uzbek</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>vai</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('vai')"">Vai</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ven</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ven')"">Venda</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>vie</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('vie')"">Vietnamese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>vol</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('vol')"">Volapük</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>vot</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('vot')"">Votic</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>wak</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('wak')"">Wakashan languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>wln</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('wln')"">Walloon</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>war</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('war')"">Waray</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>was</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('was')"">Washo</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>wel</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('wel')"">Welsh</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>fry</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('fry')"">Western Frisian</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>wal</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('wal')"">Wolaitta; Wolaytta</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>wol</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('wol')"">Wolof</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>xho</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('xho')"">Xhosa</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>sah</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('sah')"">Yakut</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>yao</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('yao')"">Yao</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>yap</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('yap')"">Yapese</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>yid</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('yid')"">Yiddish</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>yor</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('yor')"">Yoruba</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>ypk</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('ypk')"">Yupik languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>znd</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('znd')"">Zande languages</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>zap</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('zap')"">Zapotec</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>zza</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('zza')"">Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>zen</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('zen')"">Zenaga</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>zha</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('zha')"">Zhuang; Chuang</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>zul</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('zul')"">Zulu</a></td></tr>" 
    Response.write "<tr><td width=150 align=center>zun</td><td width=20>&nbsp;</td><td width=270><a href=""javascript:returncode('zun')"">Zuni</a></td></tr>" 
	Response.Write("</table>")		
%>

</body>
</html>
